name: HoC badge
on:
  push:
    branches: [ "main" ]
jobs:
  hits_counter_job:
    name: Generate and deploy HoC-badge
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: MikhailEpatko/hoc-badge-action@v3.2.1
        with:
          dir: ./src
          since: 2025-11-08
          output_dir: hoc-badge
      - uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          publish_dir: ./hoc-badge
          publish_branch: hoc-badge
          github_token: ${{ github.token }}
